package QuadTree;

import java.util.UUID;

/**
 * Represent any data, which can be inserted into quad tree.
 * Because data inserted into quad tree needs to have coordinates,
 * this class holds data of type T - so we can put there anything,
 * and at the same time class contains coordinates of data ensuring every
 * data which we want to insert into quadtree has coordinates. Class
 * also contains primary key which is generated by UUID random generator of
 * unique key.
 */

// TODO dopis popis triedy ked sa v tom sama zorientujes...
// TODO potrebujes zabezpecit enkapuslaciu.
// Asi to neni koser si myslim. Akoze tie gettre...minimalne tie cooridantes

public class Data<T> { //} extends Comparable<T>> {
    private T data;
    //private UUID primaryKey;
    private int id;
    private Coordinates coordinates;

    public Data(T parData, Coordinates parCoordinates, int parId) {
        this.data = parData;
        this.coordinates = parCoordinates;
    }

    public Data(T parData, Coordinates parCoordinates) {
        this.data = parData;
        this.coordinates = parCoordinates;
    }

    public T getData() {
        return this.data;
    }

    public Coordinates getCoordinates() {
        return this.coordinates;
    }

//    public UUID getPrimaryKey() {
//        return this.primaryKey;
//    }

    public int getId() {
        return this.id;
    }
}